### ISSUE TITLE
请问这个实现库还在维护吗？

### ISSUE THREAD

**Issue by 88250** [open-spaced-repetition/go-fsrs#1]

**Comment by L-M-Sherlock** [comment]
fsrs 在两个月前经历了一次重构，目前只有 fsrs4anki 在维护。fsrs4remnote 其实也实现了，但还没测试。

**Comment by 88250** [comment]
好的，谢谢。

**Comment by ImSingee** [comment]
原来 fsrs 重构了🌚 我看看近期安排下时间更新下吧

**Comment by L-M-Sherlock** [comment]
> 原来 fsrs 重构了🌚 我看看近期安排下时间更新下吧

重构的有点多😇，我最近也看一下。
