### ISSUE TITLE
go get -u (deprecated) changed to go install

### ISSUE THREAD

**Issue by rwxrob** [open-spaced-repetition/go-fsrs#10]

**Comment by ImSingee** [comment]
Are u robot? This is a library not a binary. Only go get can be used

**Comment by rwxrob** [comment]
Do I need to quote the manual to you? `go get -u` had *never* been the official way to install anything. It has always been `go install github.com/open-spaced-repetition/go-fsrs@latest` and you have always been doing it wrong. This will be fun to show in my example of bad Go code tomorrow in my Twitch stream. You have no idea how to write Go code and closing these tickets without even a little research is just plain bad practice and rude. I'm not a bot. I'm just fast at doing issues because I actually know about `gh` which you likely never use.
