### ISSUE TITLE
Useage question

### ISSUE THREAD

**Issue by matt-savvy** [open-spaced-repetition/go-fsrs#15]
Hello, I'm trying to incorporate this into my project but am not sure that I'm using it correctly. 

When a new card is added, a score of `fsrs.Easy` will schedule it for 11 days out, wheras all other ratings will schedule it for the same day it was created .  

```go
// adding a card to the DB for the first time
        card := fsrs.NewCard()

// grading a card 
	params := fsrs.DefaultParam()
	schedulingMap := params.Repeat(card, time.Now())
	cardInfo, ok := schedulingMap[fsrs.Rating(score)]
	if !ok {
		...
	}

	updatedCard := cardInfo.Card
        // then updating the row in the DB with all of the values from updatedCard
```

When a card is first added to the DB, do any of the values need to be updated from what `NewCard` returns? Is there some other initialization I should be doing?

Thanks

**Comment by L-M-Sherlock** [comment]
You don't need to do any other initialization.

For reference, you can check https://github.com/siyuan-note/riff. It's the spaced repetition system for SiYuan Note, which employs FSRS as the scheduler.
