### ISSUE TITLE
[TODO] switch of enable/disable short-term schedule

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/go-fsrs#19]
The implementation of ts-fsrs:
- https://github.com/open-spaced-repetition/ts-fsrs/pull/100

**Comment by domino14** [comment]
Would you have an explanation of how the long term and short term scheduler differ? Are the weights/parameters changing?

**Comment by domino14** [comment]
Could you please explain how both schedulers can follow the same learning/forgetting curves yet be far off in the time intervals?

**Comment by L-M-Sherlock** [comment]
> be far off in the time intervals

What do you mean by that?

**Comment by L-M-Sherlock** [comment]
> be far off in the time intervals

What do you mean by that?

**Comment by domino14** [comment]
> > be far off in the time intervals
> 
> What do you mean by that?

I have this simple example:

```go
package main

import (
	"fmt"
	"time"

	"github.com/open-spaced-repetition/go-fsrs/v3"
)

// Some experimentation code to figure out this API.
func main() {
	p := fsrs.DefaultParam()
	p.EnableShortTerm = true
	p.EnableFuzz = true
	card := fsrs.NewCard()
	now := time.Now()
	card.Due = now
	f := fsrs.NewFSRS(p)

	for range 4 {
		schedulingCards := f.Repeat(card, card.Due)
		rating := fsrs.Good
		card = schedulingCards[rating].Card
		revlog := schedulingCards[rating].ReviewLog
		fmt.Println("state", revlog.State)
		fmt.Println("due", card.Due)
	}
}
```

If `EnableShortTerm` is true, I get this output (I know it's random but they're all fairly similar):

```
state 0
due 2024-10-13 23:14:10.467279286 -0400 EDT m=+600.000060401
state 1
due 2024-10-18 23:14:10.467279286 -0400 EDT m=+432600.000060401
state 2
due 2024-11-06 22:14:10.467279286 -0500 EST m=+2074200.000060401
state 2
due 2025-01-16 22:14:10.467279286 -0500 EST m=+8208600.000060401
```

If `EnableShortTerm` is false, I get this output:

```
state 0
due 2024-10-16 23:05:23.993977901 -0400 EDT m=+259200.000015501
state 2
due 2024-10-31 23:05:23.993977901 -0400 EDT m=+1555200.000015501
state 2
due 2024-12-28 22:05:23.993977901 -0500 EST m=+6566400.000015501
state 2
due 2025-06-15 23:05:23.993977901 -0400 EDT m=+21168000.000015501
```

The final due date for the long-term scheduler is 5 months after the final due date for short-term scheduler. Wouldn't this mean that the parameters can't be the same? The user is much more likely to have forgotten the info if using the long-term scheduler?

**Comment by L-M-Sherlock** [comment]
You cannot assume the users with different scheduler have the same scheduler.

**Comment by domino14** [comment]
I'm sorry, I don't fully understand. My thought was that FSRS's default parameters were tuned to have recall be at 90%. I am wondering how it's possible to use two different schedulers, and rate a question "good" 4 times, and then recall would be at 90% on dates that are 5 months apart.

I feel like I am missing something about how it's supposed to work.

**Comment by L-M-Sherlock** [comment]
> My thought was that FSRS's default parameters were tuned to have recall be at 90%

Everyone has different memory pattern. That's why the optimizer is important. According to our benchmark, FSRS with optimized parameters is better than FSRS with default parameters by ~40% relatively.

**Comment by L-M-Sherlock** [comment]
> I am wondering how it's possible to use two different schedulers, and rate a question "good" 4 times, and then recall would be at 90% on dates that are 5 months apart.

Actually you need to compare the 4th review when EnableShortTerm is true with the 3rd review when EnableShortTerm is false because the 1st review when EnableShortTerm is true is done in the same day when you learn it.

**Comment by L-M-Sherlock** [comment]
There are only three ways to optimize FSRS parameters:
- https://github.com/open-spaced-repetition/fsrs-optimizer
- https://github.com/open-spaced-repetition/fsrs-rs
- https://github.com/open-spaced-repetition/fsrs-browser

**Comment by L-M-Sherlock** [comment]
By the way, this discussion has been off-topic. I recommending opening a new issue if you have more questions.
