### ISSUE TITLE
It is a bit odd that the Scheduler random seed is generated with the passed-in time

### ISSUE THREAD

**Issue by domino14** [open-spaced-repetition/go-fsrs#25]
```go
func (s *Scheduler) initSeed() {
	time := s.now
	reps := s.current.Reps
	mul := s.current.Difficulty * s.current.Stability
	s.parameters.seed = fmt.Sprintf("%d_%d_%f", time.Unix(), reps, mul)
}
```

This seed is always going to be the same string if your tests use the same time. This makes it counterintuitive to test fuzzing.

**Comment by L-M-Sherlock** [comment]
The fuzz feature is from Anki, where the seed will not change if the user doesn't do the review: https://github.com/ankitects/anki/blob/a437003d1d5b4b6000fce85755e62afe33d12fb6/rslib/src/scheduler/answering/mod.rs#L590-L609
