### ISSUE TITLE
default weights for v5 differ from the algorithm

### ISSUE THREAD

**Issue by komuw** [open-spaced-repetition/go-fsrs#26]
The default weights at https://github.com/open-spaced-repetition/go-fsrs/blob/c4552d2f4a7a841d4ea5523c74ac0995e347a289/weights.go#L5-L25   

are different from the ones in the algorithm; https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Algorithm#fsrs-5 

Is https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Algorithm the canonical specification? Which is which?

**Comment by L-M-Sherlock** [comment]
The wiki's parameters are optimized twice. I forget to update the parameters of go-fsrs. But it doesn't really matter because the previous parameters have been optimized.

**Comment by komuw** [comment]
Okay. I wanted to create my own library, just as a learning exercise and
wanted to know if I can use the wiki as the reference. Thank you.


Thanks,

Komu.
https://www.komu.engineer/about

**Comment by L-M-Sherlock** [comment]
Yes, please use the wiki as the reference. If you have any problems, please feel free to ask me.
